# Generated by Django 5.0 on 2024-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usermodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='Huzaifa', max_length=200),
        ),
    ]
